minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - docus@5.14.0
  - '@nuxt/cli@4.0.0'
  - '@nuxt/kit@4.6.0'
  - '@nuxt/nitro-server@4.6.0'
  - '@nuxt/schema@4.6.0'
  - '@nuxt/vite-builder@4.6.0'
  - '@nuxt/vite-server@4.6.0'
  - nuxt@4.6.0

trustPolicy: no-downgrade
trustPolicyExclude:
  - cssnano-preset-default@9.3.1
  - cssnano-utils@8.2.0
  - cssnano@9.3.1
  - postcss-colormin@9.0.6
  - postcss-convert-values@9.0.7
  - postcss-discard-comments@9.0.6
  - postcss-discard-duplicates@9.0.5
  - postcss-discard-empty@9.0.6
  - postcss-discard-overridden@9.0.5
  - postcss-merge-longhand@9.2.0
  - postcss-merge-rules@9.1.1
  - postcss-minify-font-values@9.0.7
  - postcss-minify-gradients@9.0.6
  - postcss-minify-params@9.0.6
  - postcss-minify-selectors@9.0.6
  - postcss-normalize-charset@9.0.5
  - postcss-normalize-display-values@9.0.5
  - postcss-normalize-positions@9.0.6
  - postcss-normalize-repeat-style@9.0.5
  - postcss-normalize-string@9.0.5
  - postcss-normalize-timing-functions@9.0.5
  - postcss-normalize-unicode@9.0.5
  - postcss-normalize-url@9.0.5
  - postcss-normalize-whitespace@9.0.5
  - postcss-ordered-values@9.0.6
  - postcss-reduce-initial@9.0.6
  - postcss-reduce-transforms@9.0.4
  - postcss-svgo@9.0.4
  - postcss-unique-selectors@9.0.5
  - semver@6.3.1
  - stylehacks@9.0.7

shellEmulator: true

packages:
  - docs
  - playground
  - examples/*

overrides:
  forges: 'workspace:*'

patchedDependencies:
  '@nuxt/ui@4.11.3': patches/@nuxt__ui@4.11.3.patch
  docus@5.14.0: patches/docus@5.14.0.patch

allowBuilds:
  better-sqlite3: false
  esbuild: false
  simple-git-hooks: true
  vue-demi: false
