minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

shellEmulator: true

packages:
  - docs
  - playground
  - examples/*

overrides:
  forges: 'workspace:*'

allowBuilds:
  better-sqlite3: false
  esbuild: false
  simple-git-hooks: true
  vue-demi: false
