import type { DocsSectionSource } from '../docs-sections.ts'
import type { ExampleFile } from '../examples.ts'
import { documentedExamples, exampleSource, repositoryUrl } from '../examples.ts'

function tree(files: ExampleFile[], base: string): string[] {
  const lines: string[] = []
  const seen = new Set<string>()
  for (const { path } of files) {
    const parts = path.split('/')
    parts.slice(0, -1).forEach((directory, depth) => {
      const key = parts.slice(0, depth + 1).join('/')
      if (!seen.has(key)) {
        seen.add(key)
        lines.push(`${'  '.repeat(depth)}- \`${directory}/\``)
      }
    })
    lines.push(`${'  '.repeat(parts.length - 1)}- [\`${parts.at(-1)}\`](${base}/${path})`)
  }
  return lines
}

const sections: DocsSectionSource = () => documentedExamples().map(({ page, name }) => {
  const { files } = exampleSource(name)
  return {
    page,
    marker: 'files',
    content: [
      '<!-- Generated by `pnpm capability-matrix`; do not edit by hand. -->',
      `::example-files{example="${name}"}`,
      ...tree(files, `${repositoryUrl()}/blob/main/examples/${name}`),
      '::',
    ].join('\n'),
  }
})

export default sections
