import type { DocsSectionSource } from '../docs-sections.ts'
import { matrixProviders } from '../capabilities.ts'

const code = (values: readonly string[]) => values.map(value => `\`${value}\``).join(', ')

const sections: DocsSectionSource = forges => matrixProviders(forges).map(({ slug, factories, provider }) => ({
  page: `4.providers/${slug}.md`,
  marker: 'header',
  content: [
    '<!-- Generated by `pnpm capability-matrix`; do not edit by hand. -->',
    `::provider-header{provider="${slug}"}`,
    '| Detail | Value |',
    '| --- | --- |',
    `| Import | \`forges/${slug}\` |`,
    `| Factories | ${code(factories.map(factory => `${factory}()`))} |`,
    `| Auth | ${code(provider.capabilities.authKinds)} |`,
    '::',
  ].join('\n'),
}))

export default sections
