import type { DocsSectionSource } from '../docs-sections.ts'
import { schemas } from '../../src/schema/index.ts'

const sections: DocsSectionSource = () => [
  { page: '5.reference/14.json-schemas.md', marker: 'schemas', content: ['<!-- Generated by `pnpm capability-matrix`; do not edit by hand. -->', Object.keys(schemas).map(name => `\`${name}\``).join(', ')].join('\n') },
]

export default sections
