import type { CapabilityInfo, GeneratedFile } from './pages.ts'
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CAPABILITY_TABLE } from '../../src/capability-table.ts'
import { ENTRIES, HIDDEN_MEMBERS, PAGES } from './config.ts'
import { extractApi } from './extract.ts'
import { buildFiles, undocumented, withoutHiddenMembers } from './pages.ts'

export interface GenerateOptions {
  /** Repository root. */
  root: string
  /** Directory to write the pages to. It may hold other pages, which are left alone. */
  outDir: string
  /** URL the pages are served under. */
  basePath?: string
}

export interface GenerateResult {
  files: GeneratedFile[]
  /** Symbols and members without a description. */
  undocumented: string[]
  /** Exports that no page selects. */
  unplaced: string[]
}

/** The banner that every generated page carries. A page with it is the output of an earlier run. */
const BANNER_RE = /^<!-- Generated by `[^`]+` from the JSDoc/m

/** Builds the API reference from the source and writes it to `outDir`. */
export function generateApiDocs({ root, outDir, basePath = '/reference' }: GenerateOptions): GenerateResult {
  const model = extractApi({ root, entries: ENTRIES })
  const { files, unplaced } = buildFiles(model, {
    basePath,
    main: 'forges',
    pages: PAGES,
    hiddenMembers: HIDDEN_MEMBERS,
    capability: capabilityOf,
    command: 'pnpm docs:api',
  })
  writeFiles(outDir, files)
  return { files, undocumented: undocumented(withoutHiddenMembers(model, HIDDEN_MEMBERS)), unplaced }
}

/** Replaces the pages of the previous run, and refuses to overwrite a file that it did not write. */
export function writeFiles(outDir: string, files: GeneratedFile[]): void {
  mkdirSync(outDir, { recursive: true })
  for (const name of readdirSync(outDir)) {
    if (name.endsWith('.md') && BANNER_RE.test(readFileSync(join(outDir, name), 'utf8'))) {
      rmSync(join(outDir, name))
    }
  }

  for (const file of files) {
    if (existsSync(join(outDir, file.path))) {
      throw new Error(`${join(outDir, file.path)} exists and was not generated; rename it or the generated page`)
    }
  }
  for (const file of files) {
    writeFileSync(join(outDir, file.path), file.content)
  }
}

const VERBS = new Map<string, CapabilityInfo>(
  CAPABILITY_TABLE.flatMap(entry => (entry.verbs ?? []).map(verb => [verb, {
    capability: entry.capability,
    perKind: entry.perKind,
    write: entry.write,
    account: entry.account,
  }] as const)),
)

/** The capability behind a verb. A page method such as `repos.labelsPage` shares the entry of `repos.labels`. */
function capabilityOf(verb: string): CapabilityInfo | undefined {
  return VERBS.get(verb) ?? VERBS.get(verb.replace(/Page$/, ''))
}
