import type * as Forges from '../src/index.ts'
import { CAPABILITY_TABLE } from '../src/capability-table.ts'

/** Providers as the matrix and provider pages show them, keyed by their `docs/content/4.providers/<slug>.md` page. */
export function matrixProviders(forges: typeof Forges): Array<{ slug: string, name: string, provider: Forges.ForgeProvider }> {
  const { azureDevOps, bitbucket, cursorOrigin, forgejo, gitea, gitee, github, gitlab, pushin, tangled } = forges
  const auth = { type: 'token', token: 'token' } as const
  return [
    { slug: 'github', name: 'GitHub', provider: github({ auth: { type: 'app', appId: 1, privateKey: '', installationId: 1 } }).create() },
    { slug: 'gitlab', name: 'GitLab', provider: gitlab({ auth }).create() },
    { slug: 'bitbucket', name: 'Bitbucket', provider: bitbucket({ auth }).create() },
    { slug: 'forgejo', name: 'Forgejo', provider: forgejo({ auth }).create() },
    { slug: 'gitea', name: 'Gitea', provider: gitea({ auth }).create() },
    { slug: 'gitee', name: 'Gitee', provider: gitee({ auth }).create() },
    { slug: 'azure-devops', name: 'Azure DevOps', provider: azureDevOps({ auth, organization: 'acme' }).create() },
    { slug: 'cursor-origin', name: 'Cursor Origin', provider: cursorOrigin({ auth }).create() },
    { slug: 'pushin', name: 'pushin.eu', provider: pushin({ auth }).create() },
    { slug: 'tangled', name: 'Tangled', provider: tangled({ auth: { type: 'app_password', identifier: 'handle', password: 'password' }, notificationsUrl: 'https://notifications.example' }).create() },
  ]
}

const KINDS: Record<string, string> = { issue: 'issue', pull_request: 'PR', discussion: 'discussion', commit: 'commit', dependency: 'dependency', code_scanning: 'code scanning', secret: 'secret', advisory: 'advisory' }

function cell(value: unknown): string {
  if (value === true) {
    return '✅'
  }
  if (value === false || value === undefined) {
    return '❌'
  }
  if (Array.isArray(value)) {
    return value.map(item => `\`${item}\``).join(', ')
  }
  if (typeof value === 'object' && value) {
    const entries = Object.entries(value).filter(([, support]) => support)
    return entries.map(([kind, support]) => support === true ? KINDS[kind] : `${KINDS[kind]} (${support})`).join(', ') || '❌'
  }
  return String(value)
}

function at(capabilities: Forges.ForgeCapabilities, path: string): unknown {
  return path.split('.').reduce<unknown>((value, key) => (value as Record<string, unknown> | undefined)?.[key], capabilities)
}

/** One row per capability the table produces, in table order. */
const rows: Array<[string, (capabilities: Forges.ForgeCapabilities) => unknown]> = (CAPABILITY_TABLE)
  .filter(entry => !entry.alias)
  .map(entry => [
    entry.capability,
    entry.capability === 'limits'
      ? (c: Forges.ForgeCapabilities) => c.limits ? Object.entries(c.limits).map(([key, length]) => `${key.replace('Length', '')} ${length}`).join(', ') : 'unknown'
      : (c: Forges.ForgeCapabilities) => at(c, entry.capability),
  ])

/** The capability matrix across every provider, as a Markdown table. */
export function matrix(forges: typeof Forges): string {
  const providers = matrixProviders(forges)
  return [
    `| Capability | ${providers.map(({ name }) => name).join(' | ')} |`,
    `| --- | ${providers.map(() => '---').join(' | ')} |`,
    ...rows.map(([name, read]) => `| \`${name}\` | ${providers.map(({ provider }) => cell(read(provider.capabilities))).join(' | ')} |`),
  ].join('\n')
}

const START = '<!-- capabilities:start -->'
const END = '<!-- capabilities:end -->'

/** One provider's capabilities, as the generated section of its page. */
export function providerSection(provider: Forges.ForgeProvider): string {
  return [
    '## Capabilities',
    '',
    'Generated by `pnpm capability-matrix`; do not edit by hand.',
    '',
    '| Capability | Support |',
    '| --- | --- |',
    ...rows.map(([name, read]) => `| \`${name}\` | ${cell(read(provider.capabilities))} |`),
  ].join('\n')
}

/** Replaces the text between the capability markers of a Markdown page. */
export function withSection(page: string, section: string): string {
  const start = page.indexOf(START)
  const end = page.indexOf(END)
  if (start < 0 || end < start) {
    throw new Error('Page has no capability markers')
  }
  return `${page.slice(0, start + START.length)}\n${section}\n${page.slice(end)}`
}
