import type { PagesOptions } from '../../scripts/api-docs/pages.ts'
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, describe, expect, it } from 'vitest'
import { ENTRIES } from '../../scripts/api-docs/config.ts'
import { extractApi } from '../../scripts/api-docs/extract.ts'
import { generateApiDocs, writeFiles } from '../../scripts/api-docs/generate.ts'
import { slug } from '../../scripts/api-docs/markdown.ts'
import { buildFiles } from '../../scripts/api-docs/pages.ts'
import { fake } from '../../src/fake/index.ts'
import * as forges from '../../src/index.ts'

const root = fileURLToPath(new URL('../../', import.meta.url))
const directories: string[] = []

function temporary(): string {
  const directory = mkdtempSync(join(tmpdir(), 'api-docs-'))
  directories.push(directory)
  return directory
}

afterAll(() => {
  for (const directory of directories) rmSync(directory, { recursive: true, force: true })
})

const BANNER = '<!-- Generated by `pnpm docs:api` from the JSDoc and types in `src/`. Do not edit. -->'

const OPTIONS: PagesOptions = {
  basePath: '/api',
  main: 'pkg',
  pages: [
    { slug: 'functions', title: 'Functions', description: 'Functions.', sections: [{ names: [/^(?:greet|shout|ANSWER)$/] }] },
    { slug: 'types', title: 'Types', description: 'Types.', sections: [{ title: 'Options', names: ['GreetOptions', 'Base', 'Mood'] }, { title: 'Errors', source: /entry/ }] },
  ],
  capability: () => undefined,
  command: 'pnpm docs:api',
}

const SAMPLE = `
export interface Base {
  /** The identifier. */
  id: string
}

/** Options for {@link greet}, with a <tag>. */
export interface GreetOptions extends Base {
  /** Shout it. */
  loud?: boolean
  nested: {
    /** Deep value. */
    value: number
  }
}

/** How to say it. */
export type Mood = 'happy' | 'sad'

/** The answer. */
export const ANSWER = 42

/** Failure. */
export class SampleError extends Error {
  /** The code. */
  readonly code: number
  constructor(message: string, code: number) {
    super(message)
    this.code = code
  }
}

/**
 * Says hello.
 *
 * @param name - Who to greet.
 * @param options Extra settings.
 * @returns The greeting.
 * @throws SampleError when the name is empty.
 * @example
 * greet('Ada')
 */
export function greet(name: string, options: GreetOptions = { id: 'x', nested: { value: 1 } }, ...rest: string[]): string {
  return name + options.id + rest.length
}

/** A shorter way. */
export const shout = (name: string): string => name.toUpperCase()
`

function sample() {
  const directory = temporary()
  writeFileSync(join(directory, 'tsconfig.json'), JSON.stringify({ compilerOptions: { target: 'es2022', module: 'nodenext', strict: true, allowImportingTsExtensions: true, types: [] } }))
  writeFileSync(join(directory, 'entry.ts'), SAMPLE)
  return extractApi({ root: directory, entries: { pkg: 'entry.ts' }, tsconfig: 'tsconfig.json' })
}

describe('extractApi', () => {
  const symbols = new Map(sample().entries[0]!.symbols.map(symbol => [symbol.name, symbol]))

  it('reads functions with their parameters, defaults, tags and examples', () => {
    const greet = symbols.get('greet')!
    const [signature] = greet.signatures

    expect(greet.kind).toBe('function')
    expect(greet.description).toBe('Says hello.')
    expect(greet.examples).toEqual(['greet(\'Ada\')'])
    expect(signature!.params.map(param => [param.name, param.type, param.optional, param.rest])).toEqual([
      ['name', 'string', false, false],
      ['options', 'GreetOptions', true, false],
      ['rest', 'string[]', false, true],
    ])
    expect(signature!.params[0]!.description).toBe('Who to greet.')
    expect(signature!.params[1]!.default).toBe('{ id: \'x\', nested: { value: 1 } }')
    expect(signature!.returns).toEqual({ type: 'string', description: 'The greeting.' })
    expect(signature!.throws).toEqual(['SampleError when the name is empty.'])
  })

  it('treats arrow function constants as functions', () => {
    expect(symbols.get('shout')!.kind).toBe('function')
    expect(symbols.get('shout')!.signatures[0]!.returns.type).toBe('string')
  })

  it('reads constants, unions and classes', () => {
    expect(symbols.get('ANSWER')).toMatchObject({ kind: 'variable', type: '42' })
    expect(symbols.get('Mood')).toMatchObject({ kind: 'type', variants: ['\'happy\'', '\'sad\''] })
    const error = symbols.get('SampleError')!
    expect(error).toMatchObject({ kind: 'class', extends: ['Error'] })
    expect(error.constructors[0]!.params.map(param => param.name)).toEqual(['message', 'code'])
    expect(error.members.map(member => member.name)).toEqual(['code'])
  })

  it('flattens nested object types and marks inherited members', () => {
    const members = symbols.get('GreetOptions')!.members

    expect(members.map(member => [member.name, member.kind, member.inheritedFrom])).toEqual([
      ['loud', 'property', undefined],
      ['nested', 'group', undefined],
      ['nested.value', 'property', undefined],
      ['id', 'property', 'Base'],
    ])
  })
})

describe('buildFiles', () => {
  const { files, unplaced } = buildFiles(sample(), OPTIONS)
  const pages = new Map(files.map(file => [file.path, file.content]))
  const functions = pages.get('02.functions.md')!
  const types = pages.get('03.types.md')!

  it('numbers the pages after an overview that lists them', () => {
    expect([...pages.keys()]).toEqual(['01.overview.md', '02.functions.md', '03.types.md'])
    expect(pages.get('01.overview.md')).toContain('| [Types](/api/types) | Types. |')
    expect(unplaced).toEqual([])
  })

  it('writes front matter and a banner on every page', () => {
    expect(functions).toMatch(/^---\ntitle: "Functions"\n/)
    expect(functions).toContain('Do not edit')
  })

  it('renders a signature with its parameters as a table', () => {
    expect(functions).toContain('function greet(name: string, options: GreetOptions = { id: \'x\', nested: { value: 1 } }, ...rest: string[]): string')
    expect(functions).toContain('| `name` | `string` | Who to greet. |')
    expect(functions).toContain('| `options?` | [`GreetOptions`](/api/types#greetoptions) | Extra settings. Defaults to `{ id: \'x\', nested: { value: 1 } }`. |')
    expect(functions).toContain('| `...rest` | `string[]` |  |')
    expect(functions).toContain('**Returns:** `string` The greeting.')
  })

  it('writes a table for one parameter, and none for no parameters', () => {
    const shout = functions.slice(functions.indexOf('## `shout()`'))

    expect(shout).toContain('| Parameter | Type |\n| --- | --- |\n| `name` | `string` |')
  })

  it('uses a table for any number of members', () => {
    expect(types).toContain('| `loud?` | `boolean` | Shout it. |')
    expect(types.slice(types.indexOf('### `Base`'))).toContain('| `id` | `string` | The identifier. |')
  })

  it('links a type only when the whole chip can be a link', () => {
    expect(functions).not.toContain('<code>')
    expect(functions).toContain('[`GreetOptions`](/api/types#greetoptions)')
  })

  it('links documented types and escapes markup in prose', () => {
    expect(types).toContain('Options for [`greet`](/api/functions#greet)')
    expect(types).toContain('&lt;tag>')
    expect(types).not.toContain('{@link')
  })
})

describe('writeFiles', () => {
  it('replaces the pages of an earlier run and leaves other files alone', () => {
    const directory = temporary()
    writeFileSync(join(directory, '20.hand.md'), 'mine')
    writeFiles(directory, [{ path: '01.old.md', content: `${BANNER}\nold` }])
    writeFiles(directory, [{ path: '02.new.md', content: `${BANNER}\nnew` }])

    expect(existsSync(join(directory, '01.old.md'))).toBe(false)
    expect(readFileSync(join(directory, '02.new.md'), 'utf8')).toContain('new')
    expect(readFileSync(join(directory, '20.hand.md'), 'utf8')).toBe('mine')
  })

  it('refuses to overwrite a page that it did not write', () => {
    const directory = temporary()
    writeFileSync(join(directory, '01.hand.md'), 'mine')

    expect(() => writeFiles(directory, [{ path: '01.hand.md', content: 'generated' }])).toThrow('was not generated')
    expect(readFileSync(join(directory, '01.hand.md'), 'utf8')).toBe('mine')
  })
})

describe('the forges reference', () => {
  const outDir = temporary()
  writeFileSync(join(outDir, '20.hand.md'), '# Hand written')
  const { files, unplaced, undocumented } = generateApiDocs({ root, outDir })
  const pages = files.filter(file => file.path.endsWith('.md'))
  const content = pages.map(file => file.content).join('\n')

  it('describes every export and every method with a JSDoc comment', () => {
    expect(undocumented).toEqual([])
  })

  it('places every export on a page of the configuration', () => {
    expect(unplaced).toEqual([])
  })

  it('stays within the numbers that Git ignores, and apart from the hand-written pages', () => {
    expect(pages.map(file => file.path).filter(path => !/^(?:0[1-9]|1\d)\./.test(path))).toEqual([])
    expect(readdirSync(outDir)).toContain('20.hand.md')
  })

  it('names every page in lower case, as Nuxt Content serves it', () => {
    expect(pages.filter(file => file.path !== file.path.toLowerCase())).toEqual([])
  })

  it('documents every runtime export of every entry point', async () => {
    const model = extractApi({ root, entries: ENTRIES })
    for (const [specifier, path] of Object.entries(ENTRIES)) {
      const documented = new Set(model.entries.find(entry => entry.specifier === specifier)!.symbols.map(symbol => symbol.name))
      const exported = Object.keys(await import(join(root, path)) as object)

      expect(exported.filter(name => !documented.has(name)), specifier).toEqual([])
    }
  })

  it('documents every method of every provider namespace', () => {
    const provider = fake().create()

    for (const [name, value] of Object.entries(provider)) {
      if (typeof value !== 'object' || value === null || name === 'capabilities')
        continue
      const start = content.indexOf(`## \`provider.${name}\``)
      expect(start, `section for provider.${name}`).toBeGreaterThan(-1)
      const section = content.slice(start + 1).split(/\n## /)[0]!
      const missing = Object.keys(value).filter(method => !new RegExp(`^### \`(?:${name}\\.)?${method}(?:\\(\\))?\`$`, 'm').test(section))

      expect(missing, `provider.${name}`).toEqual([])
    }
  })

  it('documents the helpers, the provider methods and the error classes', () => {
    for (const name of ['createForges', 'supports', 'supportOf', 'parseForgeUrl']) {
      expect(content).toMatch(new RegExp(`^#{2,3} \`${name}\\(\\)\`$`, 'm'))
    }
    expect(content).toContain('### `can()`')
    expect(content).toContain('### `support()`')
    for (const name of Object.keys(forges).filter(name => name.endsWith('Error'))) {
      expect(content).toContain(`## \`${name}\``)
    }
  })

  it('leaves no unresolved links or raw markup', () => {
    const prose = content.replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '')

    expect(content).not.toContain('{@')
    expect(prose).not.toMatch(/<[A-Z]/i)
  })

  it('links only to pages and headings that exist', () => {
    const anchors = new Map<string, Set<string>>()
    for (const file of pages) {
      const path = `/reference/${file.path.replace(/^\d+\./, '').replace(/\.md$/, '')}`
      const used = new Map<string, number>()
      const ids = new Set<string>()
      const headings = [...file.content.replace(/```[\s\S]*?```/g, '').matchAll(/^#{2,6} (.+)$/gm)]
      for (const [, heading] of headings) {
        const base = slug(heading!)
        const count = used.get(base)
        used.set(base, (count ?? 0) + 1)
        ids.add(count === undefined ? base : `${base}-${count}`)
      }
      expect(ids.size, `unique headings in ${path}`).toBe(headings.length)
      anchors.set(path, ids)
    }

    const broken: string[] = []
    for (const [, target] of content.matchAll(/(?:\]\(|href=")(\/reference\/[^)\s"]*)/g)) {
      const [path, anchor] = target!.split('#') as [string, string | undefined]
      const ids = anchors.get(path)
      const handWritten = ['/reference/capability-matrix', '/reference/events', '/reference/environment-variables', '/reference/json-schemas'].includes(path)
      if (!handWritten && (!ids || (anchor && !ids.has(anchor))))
        broken.push(target!)
    }

    expect([...new Set(broken)]).toEqual([])
  })
})
